require "user.options"
require "user.keymaps"
require "user.launch"
-- require "user.plugins"
-- require "user.treesitter"
-- require "user.comment"
-- require "user.colorscheme"
-- require "user.cmp"
-- require "user.lsp"
-- require "user.lualine"
-- require "user.telescope"
-- require "user.toggleterm"
-- require "user.nvim-tree"
-- require "user.cscope_maps"
-- require "user.gitsigns"
require "user.lazy"
